default_language_version:
    python: python3

exclude: vendor

repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.0.287
      hooks:
        - id: ruff
          args: [ --fix, --show-fixes, --exit-non-zero-on-fix ]
    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
    - repo: https://github.com/ambv/black
      rev: 23.7.0
      hooks:
          - id: black
            types: [python]
            args: [--target-version=py311]