# Generated by Django 5.1.6 on 2025-02-19 17:20

import apps.bonds.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bond",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("issuer", models.CharField(max_length=400, verbose_name="Issuer")),
                (
                    "isin",
                    models.CharField(
                        max_length=12,
                        unique=True,
                        validators=[apps.bonds.validators.validate_isin],
                        verbose_name="ISIN",
                    ),
                ),
                ("face_value", models.DecimalField(decimal_places=4, max_digits=14, verbose_name="Face Value")),
                ("interest_rate", models.DecimalField(decimal_places=4, max_digits=7, verbose_name="Bond Rate")),
                ("date_added", models.DateField(verbose_name="Date Added")),
                (
                    "maturity_date",
                    models.DateField(
                        validators=[apps.bonds.validators.validate_maturity_date], verbose_name="Maturity Date"
                    ),
                ),
                (
                    "interest_frequency",
                    models.CharField(
                        choices=[
                            ("Annual", "Annual"),
                            ("Semi-annual", "Semi-annual"),
                            ("Quarterly", "Quarterly"),
                            ("Monthly", "Monthly"),
                        ],
                        default="Annual",
                        max_length=11,
                        verbose_name="Interest Frequency",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bond",
                "verbose_name_plural": "Bonds",
            },
        ),
    ]
