# Generated by Django 5.1.6 on 2025-02-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bonds", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bond",
            name="maturity_date",
            field=models.DateField(verbose_name="Maturity Date"),
        ),
    ]
